kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: "tekton"
  namespace: tekton-pipelines
spec: 
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 10Gi
  volumeName: "tekton-pv"
